function(enable_warnings)
    foreach(tgt IN LISTS ARGN)
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            target_compile_options(${tgt} PRIVATE
                -Wall -Wextra -Wshadow -Wpedantic -Werror)
        elseif (MSVC)
            target_compile_options(${tgt} PRIVATE /W4)
        endif()
    endforeach()
endfunction()
